name: Build Mac Executable

on:
  push:
    branches: [ master ]
  workflow_dispatch:    # Allows manual triggering

jobs:
  build-mac:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --add-data "images/esc-logo.png:images" --name "Auto Timesheet Checker" run.py

    - name: Upload Mac executable
      uses: actions/upload-artifact@v4
      with:
        name: mac-executable
        path: 'dist/Auto Timesheet Checker'
        retention-days: 30  # How long GitHub keeps the artifact
